### ISSUE TITLE
Feature: User can view list of Characters.

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/ajax-project#1]
## ⚙️ Feature

User can view a list of all Breaking Bad characters.

## 📐 Functionality

User will interact with a scrollable list of all characters in Breaking Bad.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View-Characters](https://user-images.githubusercontent.com/103209321/182214572-9f89632d-fd0b-4d55-b885-b56c5a0b87aa.png)
![View-Characters with images desktop](https://user-images.githubusercontent.com/103209321/182215069-3fef16b1-7c9f-4f81-a4cc-795c3bfb0050.png)

![View-Characters (1)](https://user-images.githubusercontent.com/103209321/182214718-40496b0b-1229-4da6-827a-605e6908835d.png) ![View-Characters with images mobile](https://user-images.githubusercontent.com/103209321/182215103-43ca21cf-dbd1-4bfe-a8d9-0cfb4afe0541.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add all necessary HTML and CSS to match output.
- [x] Pull image data using `XMLHTTPRequest`.
- [x] Create a `DOM Tree` to replicate output.
- [x] Use images from api to append images to the page using the `Dom Tree`.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
