### ISSUE TITLE
Feature: User can click on img to show characters full information.

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a characters full information.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on an image of a character and it will send them to a full view of the characters information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View-Characters with images desktop](https://user-images.githubusercontent.com/103209321/182220782-e6cac71e-cc63-4977-a196-50e54283c578.png)
![Full Character Info (1)](https://user-images.githubusercontent.com/103209321/182220830-ea7efd37-2f01-4003-963d-143d3f18afc9.png)
![View-Characters with images mobile](https://user-images.githubusercontent.com/103209321/182220852-773f1af9-e11c-4891-9a38-276795e8151d.png) ![Full Character info](https://user-images.githubusercontent.com/103209321/182220869-97559436-b26e-45fa-8f5d-a07c0659f50a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] listen for a `click` on any image.
- [x] if an image is clicked `swap` to the Full Character info view.
- [x] add a Home `button `to the nav-bar when on Full Character info view.
- [x] Make sure all HTML and CSS match output.
- [x] depending on what image was clicked use that character data to `append `to the Character Info card.
- [x] If the home button is clicked return to the Character list view and make sure home button is `hidden` on that view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
