### ISSUE TITLE
Feature: User can search for individual character.

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can use the search bar to find their favorite characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type out names of specific characters and the images will be filtered out until a matching character is found.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add a Search bar desktop](https://user-images.githubusercontent.com/103209321/182222557-ee1b1eb3-3fc9-4181-a3c8-b62771d3dcd6.png)
![Search a character desktop](https://user-images.githubusercontent.com/103209321/182222573-7404ef0d-884b-4b1f-a545-ff23b47aa803.png)
![Add a search bar](https://user-images.githubusercontent.com/103209321/182222585-ddef7223-7d79-4be2-93c3-b326823c69a8.png) ![search a character](https://user-images.githubusercontent.com/103209321/182222606-e8743983-0366-4417-81b5-37dd13d9e1ad.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a search bar.
- [x] Style the search bar match the output of the example.
- [x] Define a function named `filterCharacters`
  - [x] Gets the characters names.
  - [x] Checks to see if the input value in the search bar is equal to a characters name.
  - [x] If they are not equal remove the character from the page.
- [x] If the `x button` is pressed clear text from search bar and return all characters to page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
