### ISSUE TITLE
Feature: User can view random Death info.

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view randomized death info from a character.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press a button on the nav bar that will send them to a view with a random death info card, as well as a button to regenerate another random death.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add a view death button desktop](https://user-images.githubusercontent.com/103209321/182223362-afe3bb62-e398-4ce2-8972-0bf346f03331.png)
![Death Info after click desktop (1)](https://user-images.githubusercontent.com/103209321/183127924-09ff29ea-f65b-4310-94b2-ec7a0951e512.png)
![Add a random death button](https://user-images.githubusercontent.com/103209321/182223422-0310c869-9c00-480d-b19f-2babadea9ee0.png) ![Death info after click (1)](https://user-images.githubusercontent.com/103209321/183128040-eab32e11-7cd2-4e83-92ff-d832990f3f95.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `button` to the left side of navbar.
- [x] Add necessary styling to the button to match output.
- [x] make a dummy output to match finished output.
- [x] If the button is clicked view swap to an empty page and remove button from navbar.
- [x] Define a function named `randomDeathInfo` that
  - [x] Pulls data from api
  - [x] create a dom tree to match dummy output
  - [x] append dom tree to empty page using data from api
- [x] Remove dummy output.
- [x] Add a `button` underneath the appended info card.
- [x] Match the styling of the button to finished output.
- [x] If the button is clicked remove current death info card and replace with another randomized death.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
