### ISSUE TITLE
Feature: User can view random quote.

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view randomized quote from a Breaking Bad character.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press a button on the nav bar that will send them to a view with a random quote, as well as a button to regenerate another random quote.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add a view quotes button desktop](https://user-images.githubusercontent.com/103209321/182231253-cd05873a-5b59-444e-9fa5-c0f934e4fa72.png)
![Quote after click desktop (1)](https://user-images.githubusercontent.com/103209321/183128437-e0f5085d-fce0-405f-9bb5-1b72fb553193.png)
![Add a random quote button](https://user-images.githubusercontent.com/103209321/182231293-49639212-8892-4fb5-ad80-50316fe3286e.png)  ![Quote after click (1)](https://user-images.githubusercontent.com/103209321/183128453-01bed817-bc00-4f33-8002-4cf86aead8d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a quotes `button` to the right side of NavBar.
- [x] Make a dummy output to match finished output.
- [x] If the button is `clicked` view swap to an empty page and have button removed from NavBar.
- [x] Define a function named `renderQuotes` that.
  - [x] Pulls a random quote from api.
  - [x] Creates a DOM tree that matches dummy output.
  - [x] Append the DOM tree to the page using data from the api.
- [x] If the quotes button from the NavBar is clicked run the function.
- [x] Add a Generate Random Quotes `button` underneath the header.
- [x] Match the styling to the finished output.
- [x] If the button is `clicked` run `renderQuotes`.
  - [x] The quote should be replaced by a new quote everytime the button is clicked without reloading the page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
